#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys,subprocess
#from StringIO import StringIO
if __name__ == '__main__':
	if len(sys.argv)==2:
		classname=sys.argv[0]
		createstmt=None
		try: createstmt=sys.stdin.read()
		except KeyboardInterrupt: print 'Canceled'
		if createstmt: 
			with open(classname+'.java','w') as fout:
				subprocess.Popen(
					['python','sql2java.py',classname],
					stdin=sys.stdout,stdout=fout)
				print createstmt
	else: print 'Usage: mkinf ClassName'
		
