package com.shafts.database;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * JobInfo
 * This class is automatically generated by 'sql2java.py'.
 * @author Alex
 */
public class JobInfo implements IConvertableFromResultSet{

	/**
	 * Field for column `id`.
	 */
	public Integer id;

	/**
	 * Field for column `uid`.
	 */
	public Integer uid;

	/**
	 * Field for column `title`.
	 */
	public String title;

	/**
	 * Field for column `status`.
	 */
	public Integer status;

	/**
	 * Default constructor
	 */
	public JobInfo(){ }

	/**
	 * Data from a ResultSet.
	 * @param rs the ResultSet
	 * @throws SQLException
	 */
	public JobInfo(ResultSet rs) throws SQLException{ 
		this.fromResultSet(rs); 
	}

	/**
	 * Data from arguments.
	 * @param id Value for column `id`
	 * @param uid Value for column `uid`
	 * @param title Value for column `title`
	 * @param status Value for column `status`
	 */
	public JobInfo( Integer id, Integer uid, String title, Integer status ){
		this.id=id;
		this.uid=uid;
		this.title=title;
		this.status=status;
}

	/**
	 * Getter method for field `id`.
	 * @return Value for column `id`
	 */
	public Integer getId(){
		return this.id;
	}
	
	/**
	 * Setter method for field `id`.
	 * @param v Value for column `id`
	 */
	public void setId(Integer v){
		this.id=v;
	}

	/**
	 * Getter method for field `uid`.
	 * @return Value for column `uid`
	 */
	public Integer getUid(){
		return this.uid;
	}
	
	/**
	 * Setter method for field `uid`.
	 * @param v Value for column `uid`
	 */
	public void setUid(Integer v){
		this.uid=v;
	}

	/**
	 * Getter method for field `title`.
	 * @return Value for column `title`
	 */
	public String getTitle(){
		return this.title;
	}
	
	/**
	 * Setter method for field `title`.
	 * @param v Value for column `title`
	 */
	public void setTitle(String v){
		this.title=v;
	}

	/**
	 * Getter method for field `status`.
	 * @return Value for column `status`
	 */
	public Integer getStatus(){
		return this.status;
	}
	
	/**
	 * Setter method for field `status`.
	 * @param v Value for column `status`
	 */
	public void setStatus(Integer v){
		this.status=v;
	}

	public void fromResultSet(ResultSet r) throws SQLException{
		this.id=r.getInt(1);
		this.uid=r.getInt(2);
		this.title=r.getString(3);
		this.status=r.getInt(4);
	}
}

/*Generator input:
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0

*/
